services:
  dev:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
    command: npm run start:dev

