services:
  dev:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
      PROTOCOL: http
      DOMAIN: localhost
      PORT: 3000
      DISPLAY_PORT: 3001
      JWT_SECRET: jwt_secret
      JWT_EXPIRY: 1d
      SESSION_SECRET: session_secret
      CONFIG_DB_HOST: config_mongo
      CONFIG_DB_PORT: 27017
      CONFIG_DB_NAME: db
    command: npm run start:dev
    depends_on:
      - config_mongo

  config_mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: db