services:
  prod:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
      MONGO_HOST: config_mongo
      MONGO_PORT: 27017
      MONGO_DB: db
    command: npm run start
    depends_on:
      - config_mongo

  config_mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: db
